name: Fake test 3

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Fake test 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run sleep
        run: sleep 10