name: Nyx workflow
on: [push]
# Avoid running multiple pipelines concurrently to avoid overlapping releases and tags
concurrency:
  group: project
  cancel-in-progress: false

jobs:
  infer-version:
    name: Publish the release (if any) with Nyx
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Run nyx Infer
      id: nyx-infer
      uses: mooltiverse/nyx-github-action@main
      with:
        command: infer
      env:
        NYX_VERBOSITY: 'INFO'

    - name: Bump chart versions
      if: steps.nyx-infer.outputs.newVersion == 'true'
      run: |
        ./scripts/publish.sh ${{ steps.nyx-infer.outputs.version }}
        echo "VALUES"
        cat helm/workflow-poc/values.yaml
        echo "CHAT"
        cat helm/workflow-poc/Chart.yaml

    - name: Move CHANGELOG.md to increment
      if: github.ref_name == 'main'
      run: |
        mv CHANGELOG.md changelog.old || true

    - name: Nyx publish
      id: nyx
      uses: mooltiverse/nyx-github-action@main
      with:
        command: 'publish'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NYX_VERBOSITY: 'INFO'