name: Nyx workflow
on: [push]
# Avoid running multiple pipelines concurrently to avoid overlapping releases and tags
concurrency:
  group: project
  cancel-in-progress: false

jobs:
  release-version:
    name: Publish the release (if any) with Nyx
    runs-on: ubuntu-latest
    env:
      NYX_VERBOSITY: 'INFO'

    outputs:
      newRelease: ${{ steps.nyx-publish.outputs.newRelease }}
      version: ${{ steps.nyx-publish.outputs.version }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Run nyx Infer
      id: nyx-infer
      uses: mooltiverse/nyx-github-action@main
      with:
        command: infer

    - name: Bump chart versions
      if: steps.nyx-infer.outputs.newVersion == 'true'
      run: |
        ./scripts/publish.sh ${{ steps.nyx-infer.outputs.version }}

    - name: Nyx make
      uses: mooltiverse/nyx-github-action@main
      if: steps.nyx-infer.outputs.newVersion == 'true'
      with:
        command: 'make'

    # We only generate the release notes when a new release is published and it is a core version.
    - name: Generate release notes
      if: steps.nyx-infer.outputs.newRelease == 'true' && steps.nyx-infer.outputs.coreVersion == 'true'
      run: |
        mv RELEASE_NOTES.md RELEASE_NOTES.old
        cat CHANGELOG.md RELEASE_NOTES.old >> RELEASE_NOTES.md
        rm RELEASE_NOTES.old

    - name: Nyx publish
      id: nyx-publish
      uses: mooltiverse/nyx-github-action@main
      with:
        command: 'publish'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
    # Nyx commits all new files that exist in the workspace.
    # As we only want to upload the packaged chart file to the current release,
    # we need to do it after the new release has been published
    - name: Package chart
      if: steps.nyx-infer.outputs.newRelease == 'true'
      run: |
        helm package -u helm/workflow-poc
    
    - name: Upload chart to release
      if: steps.nyx-infer.outputs.newRelease == 'true'
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "workflow-poc-${{ steps.nyx-infer.outputs.version }}.tgz"
        tag_name: "${{ steps.nyx-infer.outputs.version }}"

  publish-chart:
    name: Publish the chart
    runs-on: ubuntu-latest
    needs: release-version
    if: needs.release-version.outputs.newRelease == 'true'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: 'gh-pages'
    
    - name: Run Helm index
      run: |
        helm repo index --url  https://github.com/alpiquero/nyx-test/download/${{ needs.release-version.outputs.version }}/ --merge index.yaml .

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update index.yaml"
        commit_user_name: "${{ github.actor }}"
        commit_user_email: "${{ github.actor }}@users.noreply.github.com"
        file_pattern: "index.yaml"
        branch: "gh-pages"
        skip_checkout: true
